[tool.poetry]
name = "ml projects "
version = "0.1.0"
description = ""
authors = ["moseskortu <moses.kortu@student.ie.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
